image: artifacts.mitre.org:8200/node:6

before_script:
  - export http_proxy=http://gatekeeper.mitre.org:80
  - export https_proxy=http://gatekeeper.mitre.org:80
  - export HTTP_PROXY=http://gatekeeper.mitre.org:80
  - export HTTPS_PROXY=http://gatekeeper.mitre.org:80
  - export no_proxy=*.local,169.254/16,*.mitre.org
  - yarn

test:
  script:
  - yarn test

lint:
  script:
  - yarn run lint